### ISSUE TITLE
More contributors needed

### ISSUE THREAD

**Issue by igavelyuk** [abhijitparida/hacktobermap#389]
More contributors needed

- [ ] Watch

- [ ] Star

- [ ] Fork
-------------------------
- [ ] go to your repo

- [ ] git clone your repo path

- [ ] edit

- [ ] git commit -am "New Update"

- [ ] git push

Go to github to your project and make merge request

**Comment by abhijitparida** [comment]
Thanks for creating the issue. I have been traveling a lot recently and can't really handle the volume of new pull requests at the moment.

I will create a proper issue to attract new Hacktoberfest participants when I am ready.
